export default {
    SAMPLE: 'SAMPLE',
    UPDATE_CURRENT_ROUTE: 'UPDATE_CURRENT_ROUTE',
    SET_BOTTOM_SHEET: 'SET_BOTTOM_SHEET',
    CLOSE_BOTTOM_SHEET: 'CLOSE_BOTTOM_SHEET',
    POST_TRANSACTION: 'POST_TRANSACTION',
    SHOW_GLOBAL_LOADER: 'SHOW_GLOBAL_LOADER',
    HIDE_GLOBAL_LOADER: 'HIDE_GLOBAL_LOADER',
    SHOW_ALERT: 'SHOW_ALERT',
    CLOSE_ALERT: 'CLOSE_ALERT',
    FETCH_OFFERS: 'FETCH_OFFERS',
    POPULATE_OFFERS: 'POPULATE_OFFERS'
}